# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
stripe_api_key: sk_test_0awhnP9RUTQzJM8yAtQBjOVR00IU7A5wQ4
stripe_publishable_key: pk_test_8d9DnbXsm4fiXat02GRa8vlB00bxPEdbHz
#
# production:
  stripe_api_key: sk_test_0awhnP9RUTQzJM8yAtQBjOVR00IU7A5wQ4
  stripe_publishable_key: pk_test_8d9DnbXsm4fiXat02GRa8vlB00bxPEdbHz
